CREATE DATABASE test4;
USE test4;

CREATE TABLE t1 (a INT);
LOCK TABLE t1 WRITE;
CREATE TABLE IF NOT EXISTS t1 (s DATE GENERATED ALWAYS AS ('2000-01-01') STORED, e DATE, PERIOD FOR app(s,e));
 
# Cleanup
DROP TABLE t1;