# unresolved
# issue 27520
# segmentation fault using tensorflow debugger
FROM tensorflow/tensorflow:1.13.0rc2-py3
RUN pip install --upgrade pip && pip install pandas
COPY ./test.py /test.py
#RUN python3 /test.py
