CREATE DATABASE test;
USE test;
CREATE TABLE IF NOT EXISTS t1 (i INT);
DROP FUNCTION IF EXISTS f1;
DELIMITER $$
CREATE FUNCTION f1() RETURNS VARCHAR(16383)
BEGIN
  RETURN 'test';
END;
$$
DELIMITER ;
CREATE OR REPLACE TABLE t1 AS SELECT f1();