CREATE DATABASE test;
USE test;
SET sql_mode='ORACLE';
CREATE OR REPLACE TABLE t1 (c VARCHAR(16), KEY(c)) ENGINE=MyISAM;
INSERT INTO t1 VALUES ('foo');
DELIMITER $$
CREATE OR REPLACE FUNCTION f1() RETURN VARCHAR(16)
IS
  v t1%ROWTYPE;
BEGIN
  IF v = 'bar' THEN
    NULL;
  END IF;
  RETURN 'qux';
END $$
DELIMITER ;
SELECT f1();