CREATE DATABASE test;
use test;
CREATE TABLE t1 (c1 VARCHAR(8)) ENGINE=MyISAM;
INSERT INTO t1 VALUES ('foo'),('bar');
CREATE TABLE t2 (c2 VARCHAR(8)) ENGINE=MyISAM;
INSERT INTO t2 VALUES ('foobar'),('qux');
 
# Same with INTERSECT instead of EXCEPT
 
SELECT * FROM t1 EXCEPT SELECT * FROM t2
ORDER BY MATCH(c1) AGAINST('abc' IN BOOLEAN MODE);