--- Makefile	2005-08-30 11:30:11.000000000 -0400
+++ Makefile	2020-04-02 03:43:21.690480843 -0400
@@ -2,7 +2,7 @@
 SHELL=/bin/sh
 
 # Compiler to use
-CC=g++
+CC=wllvm++
 
 # Where you want pbzip2 installed when you do 'make install'
 PREFIX=/usr
@@ -11,16 +11,16 @@
 
 # Standard pbzip2 compile
 pbzip2: pbzip2.cpp
-	$(CC) -O3 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -o pbzip2 pbzip2.cpp -pthread -lpthread -lbz2
+	$(CC) -I lib/bzip2-1.0.6 -Llib/bzip2-1.0.6 -O0 -g -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -o pbzip2 pbzip2.cpp -pthread -lpthread -lbz2
 
 # Choose this if you want to compile in a static version of the libbz2 library
 pbzip2-static: libbz2.a pbzip2.cpp
-	$(CC) -O3 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -o pbzip2 pbzip2.cpp -pthread -lpthread -I. -L. -lbz2
+	$(CC) -O0 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -o pbzip2 pbzip2.cpp -pthread -lpthread -I. -L. -lbz2
 
 # Compatability mode for 32bit file sizes (less than 2GB) and systems
 # that have compilers that treat int as 64bit natively (ie: modern AIX)
 pbzip2-compat: pbzip2.cpp
-	$(CC) -O3 -o pbzip2 pbzip2.cpp -pthread -lpthread -lbz2
+	$(CC) -O0 -o pbzip2 pbzip2.cpp -pthread -lpthread -lbz2
 
 # Install the binary pbzip2 program and man page
 install: pbzip2
