CREATE DATABASE test;
USE test;
CREATE OR REPLACE FUNCTION f1() RETURNS DATETIME RETURN '2001-01-01 10:20:30';
CREATE OR REPLACE TABLE t1
(
   x INT,
   start_timestamp BIGINT UNSIGNED GENERATED ALWAYS AS ROW START,
   end_timestamp BIGINT UNSIGNED  GENERATED ALWAYS AS ROW END,
   PERIOD FOR SYSTEM_TIME(start_timestamp, end_timestamp)
) ENGINE=InnoDB WITH SYSTEM VERSIONING;
SELECT * FROM t1 FOR SYSTEM_TIME AS OF f1();