CREATE DATABASE test;
USE test;
CREATE TABLE `t` (
`id` int,
`d` date
) ENGINE=myisam
PARTITION BY RANGE COLUMNS(d)
(PARTITION p1 VALUES LESS THAN (MAXVALUE));
 
ALTER TABLE  t reorganize PARTITION p1 INTO (
PARTITION p2,
PARTITION p3 VALUES LESS THAN (MAXVALUE));