CREATE DATABASE test;
USE test;
SET use_stat_tables= PREFERABLY;
 
CREATE TABLE t1 (pk INT PRIMARY KEY, t CHAR(60)) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1,'foo'),(2,'bar');
ANALYZE TABLE t1;
CREATE OR REPLACE TABLE t1 (pk INT PRIMARY KEY, t TEXT) ENGINE=InnoDB;
SELECT MAX(pk) FROM t1;
 
# Cleanup
DROP TABLE t1;